### ISSUE TITLE
Update info on games database

### ISSUE THREAD

**Issue by ghost** [TBemme/galaxy-integration-nds#1]
> Please keep in mind that the games database that all games must draw information from is still a work-in-progress by the GOG staff. It is not currently able to be edited by the plugin, or by users. So particularly for platforms that are only available via community-integration at this time, information on the game pages may be sparse, images may be missing or have cropping issues, and games may take a while to appear before they are linked to an entry.

Considering that their database is based on IGDB + games they sell, I think the description here should be updated to reflect that edits on IGDB do make it over to the galaxy client.

**Comment by TBemme** [comment]
Thanks, I was not aware of this, and have just updated the description to mention editing the IGDB as a potential solution to some of the missing information issues.
